### ISSUE TITLE
Issue with the variable example

### ISSUE THREAD

**Issue by CodeByLine** [learn-co-curriculum/variable-readme#17]
Being relatively new, I'm reluctant to make drastic changes, but I hope someone goes in and make a change:

Example in lesson:
current_president = "Barack Obama"
puts "In 2014, the president was #{current_president}."

(It is a FACT that in 2014, Barach Obama was the US President, so conceptually, there is no point using a variable. It's like saying "Barack Obama" = "Barack Obama")

A better example (though not perfect):
US_President = "Barack Obama"
French_President = "Francois Hollande"

puts "In 2014, the President of the United States was #{US_President}" and the President of France was "#{French_President}"
puts "In 2014, the President of France was"#{French_President} and the President of the United States was #{US_President}"
You get the correct name in either case.

**Comment by AnnJohn** [comment]
Hi @CodeByLine not sure what the problem here is. While it is a fact, that still doesn't negate that we're creating a variable. We can set current_president equal to anything; we chose Barack Obama because it's actually quite sensical. 

And especially as you go further, you'll see that variables can be changes so current_president can be equal to a new string.

**Comment by CodeByLine** [comment]
The problem, for someone new to programming, is that the current example defeats the purpose of a variable--one can make a variable whatever one wants, but isn't the whole point of a variable to make things easier? If the US_President IS "Barack Obama", then what is the point of creating a variable? I can see the point of name = {whatever a user enters}, but what's the point of 
                        New_Years_Day = "January 1"   
Do you see what I am getting at? Perhaps the variable concept in Ruby is different than that of Python or other languages--in which case that needs to be explicitly.

If you get to see the questions asked from time to time by people going through this lesson, you'll see a lot of them relate to the confusion over variables.

**Comment by PeterBell** [comment]
Hi @CodeByLine thanks so much for raising this. There are two reasons we use variables - one is so we can change them, so on inauguration day we can update the US_President. Another is to make our code more readable by removing magic numbers. Fir example, new years day will always be January 1st, but by having a variable (or in some languages a constant - a variable that never changes) called new_years_day it's much clearer what the intent of my code is.

That said, thanks for the feedback, we are constantly working on improving the curriculum and will take this into account as we go through these lessons. Thanks, and keep on learning!
