### ISSUE TITLE
RubyMonk link error

### ISSUE THREAD

**Issue by orchardtree** [learn-co-curriculum/variable-readme#22]
RubyMonk on Interpolation of Variables in Strings 
https://rubymonk.com/learning/books/1-ruby-primer/chapters/5-strings/lessons/31-string-basics 

Is it just me or has RubyMonk been down for awhile...I looked into it and found a Reddit post basically confirming that it has been down for about a month. 

https://www.reddit.com/r/learnprogramming/comments/4uoqy6/rubymonk_not_working/

Odd...maybe it will come back???

**Comment by AnnJohn** [comment]
thanks for catching that @orchardtree. We removed the link from the Resource section.
