### ISSUE TITLE
Reading error messages

### ISSUE THREAD

**Issue by marksayers45** [learn-co-curriculum/variable-readme#24]
Reading error messages is not giving the right location file where the error can be found. It was saying the rspec, spec file instead of the lib folder. The line at which the error was found was not correct either. I did figure it out and passed but wanted to bring this to your attention. Thank you!!!

Mark Sayers

**Comment by Joll59** [comment]
@marksayers45 Glad you figured it out and thank you for bringing this to our attention. 
Errors you read on screen generally point to where the error is in the spec file, as in which test is failing. The key to errors is figure out which one of your methods that particular test was calling and what failed with that method.
