### ISSUE TITLE
Layout of the screen

### ISSUE THREAD

**Issue by Baruch28** [learn-co-curriculum/variable-readme#28]
![screenshot 1](https://user-images.githubusercontent.com/46585175/52570362-387b3180-2de1-11e9-9f70-9cf5909ff1ec.png)

The "I'm done" and the "Next Lesson" tabs are very hard to see and control. The screen doesn't allow everything to fit.

**Comment by drakeltheryuujin** [comment]
Hi @Baruch28! 

This request sounds like an improvement to or a problem with the Learn platform.
Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
