### ISSUE TITLE
Video Unavailable

### ISSUE THREAD

**Issue by iRachelxo** [learn-co-curriculum/variable-readme#34]
Video directly under Objectives is unavailable. 
![Screenshot 2022-01-13 172502](https://user-images.githubusercontent.com/84430716/149418684-ca56094f-a458-4c9f-a95c-00109df75fc8.png)

**Comment by AlveeM** [comment]
Hi @iRachelxo, thanks for pointing out this issue. 

The link seems to be working correctly on our main Canvas instance. Here's the link for reference:
http://learn-co-videos.s3.amazonaws.com/ruby/about-variables-ruby.mp4

Could you share your Canvas lesson URL so we can check it out?

**Comment by AlveeM** [comment]
Hi @iRachelxo I'm going to close the issue for now. If you encounter any more problems with the lesson, feel free to reopen it.

Thanks again for submitting the issue and helping us maintain the curriculum!
